[package]
name = "purpl-rs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "purpl"
path = "src/main.rs"
test = false

[build-dependencies]
embed-resource = "2.1.1"

[dependencies]
chrono = "0.4.24"
const_format = "0.2.30"
directories = "5.0.0"
enum-iterator = "1.4.0"
fern = "0.6.2"
log = "0.4"
vulkano = { version = "0.33.0", optional = true }

[dependencies.winapi]
version = "0.3.9"
features = [
    "errhandlingapi",
    "libloaderapi",
    "shellapi",
    "shlobj",
    "winbase",
    "winuser"
]

[features]
default = ["vulkan"]
vulkan = ["dep:vulkano"]
