[package]
name = "purpl-engine-2"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "purpl"
path = "src/main.rs"
test = false

[dependencies]
chrono = "0.4.24"
directories = "5.0.0"
embed-resource = "2.1.1"
enum-iterator = "1.4.0"
fern = "0.6.2"
log = "0.4"

[dependencies.winapi]
version = "0.3.9"
features = [
    "errhandlingapi",
    "libloaderapi",
    "shellapi",
    "shlobj",
    "winbase",
    "winuser"
]
