[package]
name = "texture"
version = "0.1.0"
edition = "2021"

[lib]
name = "texture"
path = "src/lib.rs"
test = false

[dependencies]
image = "0.24.6"
postcard = { version = "1.0.4", features = ["alloc"] }
serde = "1.0.160"
zstd = "0.12.3"
